version: "3.9"

networks:
  transcendence:
    name: transcendence
    driver: bridge

services:
  postgres:
    image: postgres:13.8
    container_name: postgres
    env_file:
      - ./docker/postgres.env
    environment:
      TZ: "Europe/Paris"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - transcendence

  pgadmin:
    image: dpage/pgadmin4:6.13
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - ./docker/pgadmin.env
    environment:
      TZ: "Europe/Paris"
    logging:
      driver: none
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - transcendence
  #==== frontend ===================================================================#
  frontend:
    container_name: frontend
    build: docker/frontend
    image: frontend
    env_file: docker/frontend/frontendProd.env
    depends_on:
     - backend
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./frontend:/var/www/html/
    networks:
      - transcendence
    stdin_open: true
    restart: unless-stopped

#==== backend ====================================================================#
  backend:
    container_name: backend
    build: docker/backend
    image: backend
    env_file: docker/backend/backendProd.env
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./backend:/var/www/html/backend/
    networks:
      - transcendence
    stdin_open: true
    restart: unless-stopped

volumes:
  data: