version: "3.9"

services:
  postgres:
    image: postgres:13.8
    container_name: postgres
    env_file:
      - ./docker/postgres.env
    environment:
      TZ: "Europe/Paris"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - transcendenceNetwork

  pgadmin:
    image: dpage/pgadmin4:6.13
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - ./docker/pgadmin.env
    environment:
      TZ: "Europe/Paris"
    logging:
      driver: none
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - transcendenceNetwork
volumes:
  data:

networks:
  transcendenceNetwork:
    name: transcendenceNetwork
    driver: bridge
